### ISSUE TITLE
Make embedded systems bridge available via pip

### ISSUE THREAD

**Issue by jarkenau** [aiplan4eu/embedded-systems-bridge#24]

**Comment by jarkenau** [comment]
In order to have a package on [pypi](https://pypi.org/) or [test.pypi](https://test.pypi.org/) a project must be created on aforementioned pages. I would handle this during this PR, but I also want to add you as maintainers of the projects. If you could create an account on the pages and get back to me with your usernames, so that I can invite you, would be really helpful. 

@alexander-sung @sebastianstock  @franklinselva

**Comment by alexander-sung** [comment]
Thanks for your initiative, @jarkenau! I'm just not sure if I want to be maintainer at yet another place. 🙂

**Comment by franklinselva** [comment]
Thank you @jarkenau! My username on pypi is **franklinselva**

**Comment by jarkenau** [comment]
> Your branch is up to date with 'origin/master'.
[master cef9343] Update version to 0.0.133
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: Permission to aiplan4eu/embedded-systems-bridge.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/aiplan4eu/embedded-systems-bridge/': The requested URL returned error: 403
Error: Process completed with exit code 128.

@franklinselva I think [this](https://stackoverflow.com/a/75308228) setting is missing and that's why it's failing. @sebastianstock  could you change this?

**Comment by sebastianstock** [comment]
That setting was already set.

**Comment by franklinselva** [comment]
Looks like adding a new secret has triggered the issue. I have added a fix in #31

**Comment by franklinselva** [comment]
@jarkenau I see a problem in creating the wheel file for PyPi saying the file exists. The log is [here](https://github.com/aiplan4eu/embedded-systems-bridge/actions/runs/5354977274/jobs/9712688114#step:7:35)

I think the job misses to fetch the last commit made by GitHub action bot

**Comment by jarkenau** [comment]
I don't think it misses fetching the latest commit, if you look closely in the log [here](https://github.com/aiplan4eu/embedded-systems-bridge/actions/runs/5354977274/jobs/9712688114#step:3:463) the SHA is up-to-date with the master branch. My guess is currently that something get's cached that shouldn't. 

> The command /usr/bin/git rev-parse refs/remotes/origin/master is used to obtain the commit hash (SHA-1) of the origin/master branch in a Git repository.

**Comment by franklinselva** [comment]
> I don't think it misses fetching the latest commit, if you look closely in the log [here](https://github.com/aiplan4eu/embedded-systems-bridge/actions/runs/5354977274/jobs/9712688114#step:3:463) the SHA is up-to-date with the master branch. My guess is currently that something gets cached that shouldn't.
> 
> > The command /usr/bin/git rev-parse refs/remotes/origin/master is used to obtain the commit hash (SHA-1) of the origin/master branch in a Git repository.
> 
> But I'm quite surprised that none of those errors occurred in my fork

The problem was deploy.yml was not triggered by `master` branch hence misses the last commit on master. The respective branches which jumpstart the job stays at a [different commit](https://github.com/aiplan4eu/embedded-systems-bridge/actions/runs/5354977274/jobs/9712688114#step:3:476) than the one on `master` branch. I think we are good to go now.
